import pathlib

ML_PROC = pathlib.Path("/opt/ml/processing")
INPUT_DIR = ML_PROC / "input"
SCRIPTS_DIR = ML_PROC / "scripts"

EVALUATION_CHANNEL = "evaluation"
TEST_CHANNEL = "test"
TRAIN_CHANNEL = "train"
VAL_CHANNEL = "validation"
LABELS_CHANNEL = "labels"
TRANSFORM_CHANNEL = "transform"

INPUT_TRANSFORM_DIR = INPUT_DIR / TRANSFORM_CHANNEL
INPUT_LABELS_DIR = INPUT_DIR / LABELS_CHANNEL

EVALUATION_DIR = ML_PROC / EVALUATION_CHANNEL
TEST_DIR = ML_PROC / TEST_CHANNEL
TRAIN_DIR = ML_PROC / TRAIN_CHANNEL
VAL_DIR = ML_PROC / VAL_CHANNEL
LABELS_DIR = ML_PROC / LABELS_CHANNEL

TEST_FILE_NAME = f"{TEST_CHANNEL}.jsonl"
LABELS_FILE_NAME = f"{LABELS_CHANNEL}.csv"

TEST_PATH = TEST_DIR / TEST_FILE_NAME
TRAIN_PATH = TRAIN_DIR / f"{TRAIN_CHANNEL}.csv"
VAL_PATH = VAL_DIR / f"{VAL_CHANNEL}.csv"
LABELS_PATH = LABELS_DIR / LABELS_FILE_NAME

EVALUATION_FILE_NAME = f"evaluation.json"
EVALUATION_PATH = EVALUATION_DIR / EVALUATION_FILE_NAME

DATA_FILE_NAME = f"data.csv"
DATA_PATH = INPUT_DIR / DATA_FILE_NAME

BAD = "bad"
GOOD = "good"
NEUTRAL = "neutral"
